[package]
name = "taskbar_media"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
nowhear = "0.2.0"
pollster = "0.4.0"
windows = { version = "0.62.2", features = [
    "Media_Control",
    "Foundation",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging"
]}
windows-future = "0.3"
