[package]
name = "taskbar_media"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
futures-util = "0.3"
nowhear = "0.2.0"
pollster = "0.4.0"
tokio = { version = "1", features = ["rt-multi-thread", "time", "sync", "macros"] }
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Media_Control",
    "Win32_Graphics_Gdi",
    "Win32_System_Com",
    "Win32_UI_Accessibility",
    "Win32_UI_WindowsAndMessaging"
]}
windows-future = "0.3"
winreg = "0.55.0"
